parameters:

    test.service.class: support.Service
    logger.class: org.slf4j.Logger

services:

    logger:
        class: logger.class

    test.service:
        class: test.service.class
        arguments: { logger: $logger, serv: $serv }
        tags: { name: 'some.listener', callback: 'some value' }


